env:
  commonjs: true
  es2021: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  space-before-function-paren: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  camelcase: 0
